### ISSUE TITLE
checkForUpdate error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version

### ISSUE THREAD

**Issue by danowitz** [mpoulson/Indigo-Ring#10]
I have been receiving the following error when the ring plugin tries to connect to github and check for versions.  It looks like it is also related to this [thread](http://forums.indigodomo.com/viewtopic.php?p=153980).

`Started plugin "Ring Doorbell 0.1.27"
   Ring Doorbell                   Number of devices found: 1
   Ring Doorbell                   	Front Door (id: 3111717)
   Ring Doorbell                   Checking for updates...
   Ring Doorbell Error             Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 153, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/MrSlim.indigoPlugin/Contents/Server Plugin/ghpu.py", line 88, in checkForUpdate
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/MrSlim.indigoPlugin/Contents/Server Plugin/ghpu.py", line 175, in _prepareForUpdate
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/MrSlim.indigoPlugin/Contents/Server Plugin/ghpu.py", line 97, in getUpdate
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/MrSlim.indigoPlugin/Contents/Server Plugin/ghpu.py", line 117, in getLatestRelease
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/MrSlim.indigoPlugin/Contents/Server Plugin/ghpu.py", line 145, in _GET
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1274, in connect
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

   Ring Doorbell Error             plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)`

**Comment by mpoulson** [comment]
resolved
