### ISSUE TITLE
plugin doesn't deal well with loss of internet

### ISSUE THREAD

**Issue by FlyingDiver** [mpoulson/Indigo-Ring#11]
```
   Ring Doorbell Error             Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 157, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/Ring.indigoPlugin/Contents/Server Plugin/Ring.py", line 239, in GetDoorbellEvent
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='api.ring.com', port=443): Max retries exceeded with url: /clients_api/dings/active?api_version=8&auth_token=X3wNHVPiw3H6Mke-R4Wy (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10888e9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Ring Doorbell Error             plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

**Comment by mpoulson** [comment]
Resolved in 0.1.30
